name: BinghamOhana
favicon: null
layout_spectrum: 0.5292808134108782
typography_spectrum: 0.9447697061114013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.22580402670428157
  lightness: 0.42600782797671854
  saturation: 0.749685273738578
  rhythmicContrast: 0.8397609237581491
purpose: []
